language: minimal
sudo: false
notifications:
  email:
    - tbekolay@gmail.com
cache:
  directories:
  - $HOME/miniconda

env:
  global:
    - MODE="test"
    - NUMPY="numpy"
    - SCIPY="false"
    - COVERAGE="false"

jobs:
  include:
    - stage: deploy
      if: branch =~ ^release-candidate-* OR tag =~ ^v[0-9]*
      env: MODE="deploy" PYTHON="3.6"
      deploy:
        - provider: pypi
          server: https://test.pypi.org/legacy/
          user: tbekolay
          password: $PYPI_TOKEN
          distributions: "sdist bdist_wheel"
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^release-candidate-*
            condition: $TRAVIS_TAG = ""
        - provider: pypi
          user: tbekolay
          password: $PYPI_TOKEN
          distributions: "sdist bdist_wheel"
          on:
            all_branches: true
            condition: $TRAVIS_TAG =~ ^v[0-9]*

before_install:
  - source .ci/conda.sh install

install:
  - .ci/$MODE.sh install

script:
  - .ci/$MODE.sh script

before_cache:
  - conda clean --all

after_success:
  - .ci/$MODE.sh after_success

after_script:
  - .ci/$MODE.sh after_script
